version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: discord.js
    versions:
    - 12.5.2
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.21.0
    - 7.22.0
